name: Build Arch packages

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: arch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base

    outputs:
      packages: ${{ steps.list.outputs.packages }}

    steps:
      - name: Checkout reusable repo
        uses: actions/checkout@v4

      - name: Setup container
        run: |
          chmod +x .github/scripts/setup.sh
          .github/scripts/setup.sh

      - name: Build packages
        run: |
          chmod +x .github/scripts/build.sh
          sudo -u builduser .github/scripts/build.sh "${{ inputs.path }}"

      - name: List output files
        id: list
        run: echo "packages=$(ls dist | paste -sd ',' -)" >> $GITHUB_OUTPUT

      - name: Upload packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist